USE T_SSolve;

CREATE TABLE CLIENTE
(
IDCLIENTE INT PRIMARY KEY IDENTITY
,NOMEFANTASIA VARCHAR (200) NOT NULL UNIQUE
,CNPJ INT NOT NULL UNIQUE
,RAZAOSOCIAL VARCHAR (200) NOT NULL UNIQUE
,ENDERECO VARCHAR (300) NOT NULL UNIQUE
);

CREATE TABLE COMODO
(
IDCOMODO INT PRIMARY KEY IDENTITY
,COMODO VARCHAR (200) NOT NULL UNIQUE
);

CREATE TABLE FUNCIONARIO
(
IDFUNCIONARIO INT PRIMARY KEY IDENTITY
,FUNCIONARIO VARCHAR (200) NOT NULL UNIQUE
);


CREATE TABLE SERVICO
(
IDSERVICO INT PRIMARY KEY IDENTITY
,IDCOMODO INT FOREIGN KEY REFERENCES COMODO (IDCOMODO)
,DESCRICAO VARCHAR (300) NOT NULL 
,IDCLIENTE INT FOREIGN KEY REFERENCES CLIENTE (IDCLIENTE)
,PRECO INT NOT NULL
,SINICIO DATE
,SFIM DATE
);



