USE T_SSolve;

SELECT * FROM CLIENTE;
SELECT * FROM COMODO;
SELECT * FROM FUNCIONARIO ORDER BY IDFUNCIONARIO ASC;
SELECT * FROM SERVICO ORDER BY IDSERVICO ASC;
SELECT * FROM FUNCIONARIOSERVICO;

SELECT S.*, C.NOMEFANTASIA
FROM SERVICO S 
JOIN CLIENTE C
ON S.IDCLIENTE = C.IDCLIENTE;

SELECT S.*, C.NOMEFANTASIA, M.* 
FROM SERVICO S 
JOIN CLIENTE C
ON S.IDCLIENTE = C.IDCLIENTE
JOIN COMODO M 
ON S.IDCOMODO = M.IDCOMODO;